[tasks.build]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "index", "--out-dir", "./static/build"]

[tasks.serve]
command = "simple-http-server"
args = ["-i", "./static/", "-p", "8080", "--nocache", "--try-file", "./static/index.html"]